allowCheckoutWithoutPayment: ''
allowEmptyCartOnCheckout: ''
allowPartialPaymentOnCheckout: ''
autoSetCartShippingMethodOption: ''
autoSetNewCartAddresses: ''
autoSetPaymentSource: ''
currency: USD
freeOrderPaymentStrategy: complete
handle: primary
minimumTotalPriceStrategy: default
name: Primary
orderReferenceFormat: '{{number[:7]}}'
primary: true
requireBillingAddressAtCheckout: ''
requireShippingAddressAtCheckout: ''
requireShippingMethodSelectionAtCheckout: ''
sortOrder: 99
useBillingAddressForTax: ''
validateOrganizationTaxIdAsVatId: ''
