handle: dummy
isFrontendEnabled: true
name: Dummy
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
paymentType: purchase
settings: null
sortOrder: 99
type: craft\commerce\gateways\Dummy
