color: red
description: null
fieldLayouts:
  092119c5-6fbc-4f64-9a43-45c5ea15fc94:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-31T09:56:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 694b86b3-3359-40c0-bd2e-63739dfbdb16
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T10:06:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e0024b87-7ccc-40bd-b3c5-251c7640ae62 # Type of calendar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6064e560-9c98-4c19-9fc6-cdc95e18dd7a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T10:06:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 85ff26ce-b8f0-40cb-a626-7a69b96f496b # Body Matrix - Calendar - Categories to include
            handle: null
            includeInCards: false
            instructions: null
            label: 'Categories to include'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45a4fa99-4fdb-40cc-a40e-306b4ba469e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T10:06:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e234e19d-fbcb-43d6-b1f3-ef80437ed40d # Body Matrix - Calendar - Categories to exclude
            handle: null
            includeInCards: false
            instructions: null
            label: 'Categories to exclude'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb98cb9e-b2bc-4f7b-b17d-d7d6d22fca2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff944caf-3bbf-4f56-8df4-a75f94ab9824
        userCondition: null
handle: bm_calendar
hasTitleField: true
icon: calendar
name: Calendar
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
