color: blue
description: null
fieldLayouts:
  bad5c172-7c86-4974-92a9-4eccb41584e2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-31T09:12:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38f7e2ae-2b81-4077-ad4c-ad27f54dbb4f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: abb071ea-e289-41a7-afe1-34381c6d5630 # Body Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d289d7e2-ab1f-4a28-ba36-f64127dbfb9d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c5c9840-cd72-4ace-a1e5-392e55fc884b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7aba2536-149b-48ea-a774-554028f63ab2 # Is livestreamed?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cbdeef9-a0d9-4afd-b903-7b9470613748
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea599a1c-5faa-4e2d-ad6a-133e69f09c17 # Show on Year-at-a-glance?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3303c6ea-1de1-43bd-9742-c5ffc1e6aefe
            userCondition: null
            warning: null
            width: 100
        name: Details
        uid: f82be84c-b7dc-40a5-a0b5-cbc8c7909b90
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c6dbf6b-cf9f-4681-b74a-6410bdaca77e # Show this category's individual events in the drop-down menu?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 948c4a1f-0d85-45d7-b1db-70d146bedab6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a0074f6-fe7f-4e6a-9ccb-15af242fa2ed # CSS Theme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bca55fdd-a2ed-41bb-ad2c-47b3225f608d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 11a375e3-fa35-479d-b681-edaeab6f30a0 # Page CSS File
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 329263c8-5920-4036-a588-dfb1bbf23bfa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d4dfd01-d8a4-4bf4-9d27-0ff08d2525a1 # CSS styles for this page
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b905681-08d0-4e0c-8af2-3e2fa5d8cbc7
            userCondition: null
            warning: null
            width: 100
        name: 'Advanced & Styles'
        uid: 925ed7ea-47ea-4e01-ac79-fd5b134d9712
        userCondition: null
handle: listOfEvents
hasTitleField: true
icon: bars
name: 'menu List of Events'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
