color: blue
description: null
fieldLayouts:
  b68c0b93-4ccd-47ff-815b-d5f1241a80cd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-31T09:30:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd09adb4-f02e-4aa1-b831-ffc534296f0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:32:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: abb071ea-e289-41a7-afe1-34381c6d5630 # Body Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c0c89aa-3380-4fcb-9eaf-a098391572b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9efb70b4-f6d0-4e5c-8ed3-877fc274b097
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-31T09:32:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a0074f6-fe7f-4e6a-9ccb-15af242fa2ed # CSS Theme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dc1ba9c-53d0-4263-b41c-677af30baf78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:32:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 11a375e3-fa35-479d-b681-edaeab6f30a0 # Page CSS File
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c621e1d-4cc1-4747-af46-591f9e7c8b81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:32:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d4dfd01-d8a4-4bf4-9d27-0ff08d2525a1 # CSS styles for this page
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5056ec1d-fce0-4b7e-9a9d-3c8ec49c9e99
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: 509060e2-3ca6-4274-9363-e5d8b29bf7a4
        userCondition: null
handle: menuSinglePage
hasTitleField: true
icon: bars
name: 'menu Single page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
