color: blue
description: 'Home page for a URL, such as meditationinnorthernarizona.org'
fieldLayouts:
  d1c27305-033a-48a6-8840-a55674347fd9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-31T08:53:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a5cf3a24-3021-47ab-b6e8-8b221b2f32a8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f7bab6f8-c581-4ae7-8476-8f70b5c095c3 # Main Top Branding Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 133d779c-4c20-4ed9-a48c-916dab73cc3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: abb071ea-e289-41a7-afe1-34381c6d5630 # Body Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 177bbd5b-4e45-40f7-9b2e-9620efd4077a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 770fc2f0-234c-4829-8724-bf0e3fff0ce7 # Footer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d78986b-164a-44f7-a6f5-9d7fa94fb91a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b932e96f-0e11-404e-af5e-f0aa7d32f4f1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-31T09:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a0074f6-fe7f-4e6a-9ccb-15af242fa2ed # CSS Theme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56ec5957-564d-419b-8f27-f73d2066fbc8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 11a375e3-fa35-479d-b681-edaeab6f30a0 # Page CSS File
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35259e6d-9c48-4bde-9420-f5e32464ffb7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T09:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d4dfd01-d8a4-4bf4-9d27-0ff08d2525a1 # CSS styles for this page
            handle: null
            includeInCards: false
            instructions: 'Add any CSS that is specific just to this entry or page. It will be inserted between <style> </style> tags.'
            label: 'Freeform CSS for this page'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cfebac8-7ad5-4a6d-b621-863229d19b47
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: 2b7ea401-e161-451b-ab81-1bbad2d1150a
        userCondition: null
handle: menuSiteHome
hasTitleField: true
icon: bars
name: 'menu Site Home'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
