css: '@import "/css_ckeditor.css"'
headingLevels:
  - 1
  - 2
  - 3
  - 4
name: 'Everything Bagel'
options:
  alignment:
    options:
      - left
      - center
      - right
      - justify
  fontSize:
    options:
      - tiny
      - small
      - default
      - big
      - huge
      - 30px
  heading:
    options:
      -
        class: ck-heading_paragraph
        model: paragraph
        title: Paragraph
      -
        class: ck-heading_heading1
        model: heading1
        title: 'Heading 1'
        view: h1
      -
        class: ck-heading_heading2
        model: heading2
        title: 'Heading 2'
        view: h2
      -
        class: ck-heading_heading3
        model: heading3
        title: 'Headhing 3'
        view: h3
      -
        class: ck-blockquote
        model: blockquote
        title: '"Blockquote"'
        view: blockquote
      -
        class: ck-pre
        model: pre
        title: Monospace
        view: pre
  link:
    addTargetToExternalLinks: false
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  toolbar:
    shouldNotGroupWhenFull: true
toolbar:
  - undo
  - redo
  - heading
  - fontSize
  - fontFamily
  - bold
  - italic
  - underline
  - '|'
  - fontColor
  - fontBackgroundColor
  - '|'
  - alignment
  - bulletedList
  - outdent
  - indent
  - '|'
  - link
  - insertTable
  - horizontalLine
  - sourceEditing
