altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a244f1d0-78d9-4a67-99c2-0a69907fca41:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-15T05:07:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2a78b502-f161-4c9d-a9d5-c657b373119a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 71c46b98-4514-4557-9873-fc0cca787736
        userCondition: null
fs: localPublic
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localPublic
transformSubpath: /images/transforms/
