altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b09534b9-a7ef-452b-8191-412a466c0f28:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-17T05:25:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cd3cc320-0cc0-4300-b273-c448080105b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a911248-1380-4207-8726-f01aa327d88b
        userCondition: null
fs: templatesFolder
handle: templateFiles
name: 'Template Files'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
