columnSuffix: null
handle: mainText
instructions: null
name: 'Main Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 4e23ee16-d562-4701-b7cf-46c8189c44a6 # Everything Bagel
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
