columnSuffix: null
handle: pageCssFile
instructions: 'If there is a CSS file specific to this page, give its'
name: 'Page CSS File'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: false
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:e181f57a-2fe1-4266-89d1-a6184f508542' # Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:bad21769-94f6-47e6-816d-ca69d0aa5819' # Template Files
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\SlugConditionRule
              -
                - uid
                - 6b9df691-35b9-452c-a0ef-04d2161403d9
              -
                - operator
                - ew
              -
                - value
                - css
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
