columnSuffix: null
handle: showOnYearAtAGlance
instructions: null
name: 'Show on Year-at-a-glance?'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Yes'
        -
          - value
          - 'yes'
        -
          - icon
          - 'y'
        -
          - color
          - '#865e3c'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
